# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'netflix_explorer.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NetflixExplorer(object):
    def setupUi(self, NetflixExplorer):
        NetflixExplorer.setObjectName("NetflixExplorer")
        NetflixExplorer.resize(839, 527)
        NetflixExplorer.setStyleSheet("/* Main Window */\n"
"QMainWindow {\n"
"    background-color: #121212;\n"
"    color: #ffffff;\n"
"    font-family: \'Segoe UI\', sans-serif;\n"
"}\n"
"\n"
"/* Labels */\n"
"QLabel {\n"
"    color: #ffffff;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"/* Line Edit (Search Box) */\n"
"QLineEdit {\n"
"    background-color: #1e1e1e;\n"
"    border: 1px solid #333333;\n"
"    padding: 5px;\n"
"    color: #ffffff;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"/* ComboBoxes */\n"
"QComboBox {\n"
"    background-color: #1e1e1e;\n"
"    color: #ffffff;\n"
"    border: 1px solid #333333;\n"
"    padding: 5px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"/* Buttons */\n"
"QPushButton {\n"
"    background-color: #e50914;\n"
"    color: white;\n"
"    padding: 6px 12px;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f6121d;\n"
"    padding-left: 6px;\n"
"    padding-top: 6px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #b00610;\n"
"    padding-left: 8px;\n"
"    padding-top: 8px;\n"
"}\n"
"\n"
"/* Table */\n"
"QTableWidget {\n"
"    background-color: #1e1e1e;\n"
"    color: #ffffff;\n"
"    gridline-color: #444444;\n"
"    border: 1px solid #444444;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QTableWidget::item:hover {\n"
"    background-color: #222;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #e50914;\n"
"    color: white;\n"
"    padding: 6px;\n"
"    border: none;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/* Scrollbars */\n"
"QScrollBar:vertical {\n"
"    background: #1e1e1e;\n"
"    width: 10px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #e50914;\n"
"    min-height: 20px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical {\n"
"    height: 0px;\n"
"}\n"
"\n"
"/* Tooltip */\n"
"QToolTip {\n"
"    background-color: #333;\n"
"    color: white;\n"
"    border: 1px solid #e50914;\n"
"}\n"
"\n"
"/* Checkboxes */\n"
"QCheckBox {\n"
"    color: white;\n"
"    spacing: 6px;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QCheckBox:hover {\n"
"    color: #e50914;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(NetflixExplorer)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(20, 50, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.title.setFont(font)
        self.title.setToolTipDuration(1)
        self.title.setTextFormat(QtCore.Qt.RichText)
        self.title.setObjectName("title")
        self.search_lable = QtWidgets.QLabel(self.centralwidget)
        self.search_lable.setGeometry(QtCore.QRect(300, 40, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.search_lable.setFont(font)
        self.search_lable.setToolTipDuration(1)
        self.search_lable.setObjectName("search_lable")
        self.searchbar = QtWidgets.QLineEdit(self.centralwidget)
        self.searchbar.setGeometry(QtCore.QRect(440, 40, 381, 20))
        self.searchbar.setToolTipDuration(1)
        self.searchbar.setObjectName("searchbar")
        self.genre_lable = QtWidgets.QLabel(self.centralwidget)
        self.genre_lable.setGeometry(QtCore.QRect(320, 70, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.genre_lable.setFont(font)
        self.genre_lable.setObjectName("genre_lable")
        self.genre_combobox = QtWidgets.QComboBox(self.centralwidget)
        self.genre_combobox.setGeometry(QtCore.QRect(380, 70, 141, 22))
        self.genre_combobox.setToolTipDuration(1)
        self.genre_combobox.setObjectName("genre_combobox")
        self.country_combobox = QtWidgets.QComboBox(self.centralwidget)
        self.country_combobox.setGeometry(QtCore.QRect(600, 70, 101, 22))
        self.country_combobox.setToolTipDuration(1)
        self.country_combobox.setObjectName("country_combobox")
        self.country_lable = QtWidgets.QLabel(self.centralwidget)
        self.country_lable.setGeometry(QtCore.QRect(530, 70, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.country_lable.setFont(font)
        self.country_lable.setObjectName("country_lable")
        self.movie_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.movie_checkbox.setGeometry(QtCore.QRect(670, 100, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.movie_checkbox.setFont(font)
        self.movie_checkbox.setObjectName("movie_checkbox")
        self.series_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.series_checkbox.setGeometry(QtCore.QRect(750, 100, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.series_checkbox.setFont(font)
        self.series_checkbox.setObjectName("series_checkbox")
        self.filter_botton = QtWidgets.QPushButton(self.centralwidget)
        self.filter_botton.setGeometry(QtCore.QRect(710, 70, 111, 23))
        self.filter_botton.setToolTipDuration(1)
        self.filter_botton.setObjectName("filter_botton")
        self.output_table = QtWidgets.QTableWidget(self.centralwidget)
        self.output_table.setGeometry(QtCore.QRect(10, 130, 821, 381))
        self.output_table.setToolTipDuration(1)
        self.output_table.setObjectName("output_table")
        self.output_table.setColumnCount(0)
        self.output_table.setRowCount(0)
        NetflixExplorer.setCentralWidget(self.centralwidget)

        self.retranslateUi(NetflixExplorer)
        QtCore.QMetaObject.connectSlotsByName(NetflixExplorer)

    def retranslateUi(self, NetflixExplorer):
        _translate = QtCore.QCoreApplication.translate
        NetflixExplorer.setWindowTitle(_translate("NetflixExplorer", "Netflix Explorer"))
        self.title.setText(_translate("NetflixExplorer", "Netflix Explorer"))
        self.search_lable.setText(_translate("NetflixExplorer", "Search By Title :"))
        self.genre_lable.setText(_translate("NetflixExplorer", "Genre :"))
        self.country_lable.setText(_translate("NetflixExplorer", "Country :"))
        self.movie_checkbox.setText(_translate("NetflixExplorer", "Movie"))
        self.series_checkbox.setText(_translate("NetflixExplorer", "Series"))
        self.filter_botton.setText(_translate("NetflixExplorer", "Filter"))
